name: tests-payments

on: #when we want to run this 
  pull_request:
   paths: # run only if changes are made inside this
    - 'payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2 # access all code in runner machine
     - run: cd payments && npm i && npm run test:ci
    
